services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/nba-client:latest
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/nba-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend